<a href="https://colab.research.google.com/github/jin2-web/aiSmartPlatform/blob/master/1_numpy(Student)_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
# numpy -> pandas -> matplotlib(시각화)
#       -> sklearn (ML)
#       -> kaggle
#       -> DL (CNN, RNN, GAN, Yolo5)
#       -> papago API
#       프로젝트

# Numpy
- Numerical Python
- 산술 계산을 위한 패키지
    - 다차원 배열인 ndarray는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
    - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
    - 선형대수, 난수 생성기, 푸리에 변환 가능
    
- Numpy는 일반적인 산술 데이터 처리를 위한 기본 라이브러리를 제공하기때문에 통계나 분석데이터를 처리하기 위해선 Pandas를 사용해야 한다.
- Numpy가 파이썬 산술 계산 영역에서 중요한 위치를 차지하는 이유중 하나는 대용량 데이터 배열을 효율적으로 다룰수 있도록 설계되어 있다.

In [ ]:
import numpy as np
# numpy 를 np라는 이름으로 사용하겠다.

In [ ]:
my_arr = np.arange(1000000)

In [ ]:
my_list = list(range(1000000))

In [ ]:
print(my_arr)
print(type(my_arr))

[     0      1      2 ... 999997 999998 999999]
<class 'numpy.ndarray'>


In [ ]:
print(my_list)

In [ ]:
%time
for _ in range(1000):
    my_arr2 = my_arr*2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 14.5 µs


In [ ]:
my_arr2[:20]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [ ]:
%time
for _ in range(1000):
    my_list2 = [i*2 for i in my_list]

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 5.96 µs


In [ ]:
my_list2[:20]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

### Numpy ndarray : 다차원 배열 객체
- Numpy 는 ndarray라고 하는 N차원 배열 객체를 사용한다.
- 배열은 스칼라 원소 간의 연산에서 사용하는 문법과 비슷한 방식을 사용해 전체 데이터 블록에 수학적인 연산을 수행할 수 있도록 해준다.


In [ ]:
# array를 랜덤한 숫자로 만든다.
data_0 = np.random.randn(3)

In [ ]:
data_0.shape

(3,)

In [ ]:
data_0

array([-0.00312177, -1.41380401,  1.74448827])

In [ ]:
data_1 = np.random.randn(1,10)

In [ ]:
data_1.shape

(1, 10)

In [ ]:
data_2 = np.random.randn(3,10)

In [ ]:
data_2.shape

(3, 10)

In [ ]:
data_2

array([[ 0.56761715, -0.1923818 ,  0.33418451,  2.24301696,  0.05454767,
         0.80690537,  0.53598461, -0.30128834, -0.34231456, -0.72217612],
       [ 0.01306142, -1.06824885,  0.24412549, -1.53657753,  0.16806671,
         1.09814835, -0.02108753,  1.64269635,  1.66883961, -0.44561428],
       [ 0.31704211,  0.76726542, -0.43436576,  0.42810237, -1.94417646,
         0.5046288 , -0.22883018, -1.37272761, -0.23040958, -0.48043605]])

In [ ]:
data_3 = np.random.randn(3,10,5)

In [ ]:
data_3

array([[[-2.18466771,  1.02468733,  0.08352777, -0.68018293,
         -0.9154779 ],
        [ 0.79974983, -0.11263065, -1.54430238, -0.29798157,
          2.31140484],
        [-0.42612259,  0.96006093,  0.29873491, -0.00747056,
         -0.26304483],
        [ 0.96431225, -1.32523822,  2.31626755,  1.22554365,
          0.16116469],
        [-2.29775076,  0.98153622,  0.20352441,  0.14794872,
         -0.83791595],
        [ 0.73855414,  0.07015762, -1.18770293, -1.19723938,
          1.76056378],
        [-0.61587874, -0.34554301,  1.19674694,  0.25279249,
          0.95171916],
        [-0.06429143,  0.55729197, -1.50402082, -0.88450853,
         -0.10124541],
        [ 1.55577532,  0.06496572, -0.84691804,  0.77928092,
          0.09175235],
        [-1.05672416, -1.15402629,  1.82289256, -0.47263472,
          0.35348123]],

       [[-0.12349629, -0.43216362, -0.20124702, -0.87850405,
         -0.74534158],
        [ 0.363583  , -0.58210399,  1.03367286,  0.781989  ,
          0.5

### ndarray 생성하기1
- array 함수를 이용해 배열을 생성할 수 있다.

In [ ]:
data_4 = [6,7,8,3,4,2]

In [ ]:
type(data_4)

list

In [ ]:
arr_1 = np.array(data_4)

NameError: ignored

In [ ]:
arr_1.shape

In [ ]:
data_5 = [[6,7,8,3,4,2]]

In [ ]:
arr_2 = np.array(data_5)

In [ ]:
arr_2.shape

In [ ]:
data_7 = [[[6,7,8,3,4,2]]]
arr_3 = np.array(data_7)

In [ ]:
arr_3.shape

In [ ]:
data_8 = [[[6]]]
arr_4 = np.array(data_7)

In [ ]:
arr_4.shape

In [ ]:
# list 를 이용해 array를 만들어 보세요
# 아무 숫자나 넣고 만들면 되요
# 단 4, 2 의 shape으로 만들어 보세요
list_1 = [[1,2,3,4],[4,5,6,7]]
list_2 = [[1,2], [3,4], [4,5], [6,7]]

arr_5 = np.array(list_1)
arr_6 = np.array(list_2)

In [ ]:
arr_5.shape

In [ ]:
arr_6.shape

In [ ]:
arr_6.ndim

In [ ]:
list_3 = [[1,2,3,4],[4,5,6]]

In [ ]:
np.array(["hello", "world"])*2

In [ ]:
np.mat([[1,2,3,4],[4,5,6,7]])

### ndarray 생성하기2
- np.zeros : 메모리를 초기화 하고 0 으로 채워 넣는다.
- np.empty : zeros와 비슷하지만, 메모리를 초기화 하지 않고 빈값을 넣기 때문에 0 이외의 값이 들어갈수 있다.
- np.ones : 메모리를 초기화 하고 1 로 채워 넣는다.
- np.full : 특정 값으로 채워 넣는다.  
  
- ?????_like : array의 shape 크기만큼 지정된 값으로 채워 array를 반환합니다.
  
- np. eye : NxN 단위행렬을 생성한다.

In [ ]:
list_1 = []
list_1.append(1)
print(list_1)

[1]


In [ ]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# zeros 를 이용해 3,4,5 인 array를 만들어 보세요
# 모든 숫자가 2로 채워진 3,4인 array를 만들어 보세요

In [ ]:
arr_7 = np.zeros([3,4,5])

In [ ]:
arr_7.shape

(3, 4, 5)

In [ ]:
np.full([3,4], 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
np.empty((2,2))

array([[6.92488790e-310, 0.00000000e+000],
       [6.95331465e-310, 6.95331459e-310]])

### 데이터 타입
- object.astype() : 함수를 통해 dtype을 변경할수 있다.
- 자세한 내용은 공식 문서 참고

In [ ]:
arr_6

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [ ]:
arr_6.dtype

dtype('int64')

In [ ]:
arr_6.astype(dtype="float64")

array([[1., 2.],
       [3., 4.],
       [4., 5.],
       [6., 7.]])

### numpy 배열의 산술 연산
- numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할 수 있다.
- 이를 **벡터화** 라고 한다.
- 브로드케스팅과는 다른 개념

In [ ]:
arr_1 = np.array([
    [1,2,3],
    [4,5,6]
])
# arr_1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
# 요소곱
arr_1 * arr_1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# arr_1과 arr_2의 덧셈, 뺄셈, 곱셈, 나눗셈을 해보세요. 대소 관계도 비교해 보세요 (boolean)
arr_2 = np.array([
    [2,3,4],
    [7,6,3]
])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[[ 3  5  7]
 [11 11  9]]
[[-1 -1 -1]
 [-3 -1  3]]
[[ 2  6 12]
 [28 30 18]]
[[0.5        0.66666667 0.75      ]
 [0.57142857 0.83333333 2.        ]]


In [ ]:
print(arr_1 >= arr_2)

[[False False False]
 [False False  True]]


In [ ]:
print(arr_1 != arr_2)

[[ True  True  True]
 [ True  True  True]]


In [ ]:
arr_2

array([[2, 3, 4],
       [7, 6, 3]])

In [ ]:
arr_2.transpose()

array([[2, 7],
       [3, 6],
       [4, 3]])

In [ ]:
# 행렬곱
# arr_1 과 arr_2 의 행렬곱을 해보고
# 손으로 한 결과와 np.dot 연산의 결과를 비교해 보세요
np.dot(arr_1, arr_2.transpose())


array([[20, 28],
       [47, 76]])

### 색인과 슬라이싱 기초
- 리스트와 동일하다.
- 제일 중요

In [ ]:
arr_1 =  np.arange(10)

In [ ]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_1[5]

5

In [ ]:
arr_1[5:8]

array([5, 6, 7])

In [ ]:
arr_1[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr_1[-1:]

array([9])

In [ ]:
arr_1[1] = 122222

In [ ]:
arr_1[:] = 10

In [ ]:
arr_1 = 10

In [ ]:
arr_1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

- array에 스칼라 값을 대입하면 영역 전체로 브로드캐스팅 된다.
- list와의 차이점은 배열 조각은 원본 배열의 View이다.즉, 데이터는 복사되지 않고 View에 대한변경은 그대로 원본 배열에 반영 된다.
- View 대신 ndarray의 복사본을 얻고 싶다면 object.copy() 함수를 사용해 명시적으로 배열을 복사해야 한다.

In [ ]:
arr_2 = arr_1

In [ ]:
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_1[1] = 122222

In [ ]:
arr_1

array([     0, 122222,      2,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
arr_2

array([     0, 122222,      2,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
arr_3 = arr_1.copy()

In [ ]:
arr_3

array([     0, 122222,      2,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
arr_1[2] = 1

In [ ]:
arr_1

array([     0, 122222,      1,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
arr_3

array([     0, 122222,      2,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
arr_2

array([     0, 122222,      1,      3,      4,      5,      6,      7,
            8,      9])

In [ ]:
print(id(arr_1))
print(id(arr_2))
print(id(arr_3))

140178774025840
140178774025840
140178772748752


### 블리언 값으로 선택하기
- 중복된 이름이 포함된 배열이 있다고 하자. 그리고 numpy.random 모듈이 있는 randn 함수를 사용해서 임의의 표준 정규분포 데이터를 생성하자.

In [ ]:
names = np.array(["오민엽", "이상엽", "김의석", "오민엽", "이상엽"])

In [ ]:
# 정규분포에서 값을 뽑아 (5,4) 의 shape으로 만들어 준다.
data = np.random.randn(5,4)
print(data)

[[ 0.40184267 -1.22132081  1.06841388  0.75251849]
 [ 1.09894147  1.97031227 -0.88543475  1.89301717]
 [-0.05287596  1.5335425  -0.87916185 -1.12266186]
 [ 1.29388419 -0.31233429 -0.08044291  0.28976011]
 [-1.04927325 -0.5232911  -0.10324431  1.32298411]]


In [ ]:
# - 각각의 이름은 data배열의 각 row에 대응한다고 가정하자.
names == "오민엽"

array([ True, False, False,  True, False])

In [ ]:
data[names == "오민엽"]

array([[ 0.40184267, -1.22132081,  1.06841388,  0.75251849],
       [ 1.29388419, -0.31233429, -0.08044291,  0.28976011]])

In [ ]:
bool_1 = names == "오민엽"

In [ ]:
data[~bool_1]

array([[ 1.09894147,  1.97031227, -0.88543475,  1.89301717],
       [-0.05287596,  1.5335425 , -0.87916185, -1.12266186],
       [-1.04927325, -0.5232911 , -0.10324431,  1.32298411]])

- &(and) 연산, |(or)연산 을 나타낸다.
- and, or 예약어는 사용할수 없다.

In [ ]:
# 문제 data에서 0보다 작은 값들만 필터링 해보세요
data[data < 0]
# 문제 data에서 0보다 작은 값들은 0으로 치환하세요

array([-1.22132081, -0.88543475, -0.05287596, -0.87916185, -1.12266186,
       -0.31233429, -0.08044291, -1.04927325, -0.5232911 , -0.10324431])

In [ ]:
data

array([[ 0.40184267, -1.22132081,  1.06841388,  0.75251849],
       [ 1.09894147,  1.97031227, -0.88543475,  1.89301717],
       [-0.05287596,  1.5335425 , -0.87916185, -1.12266186],
       [ 1.29388419, -0.31233429, -0.08044291,  0.28976011],
       [-1.04927325, -0.5232911 , -0.10324431,  1.32298411]])

In [ ]:
data[data < 0] = 0

In [ ]:
data

array([[0.40184267, 0.        , 1.06841388, 0.75251849],
       [1.09894147, 1.97031227, 0.        , 1.89301717],
       [0.        , 1.5335425 , 0.        , 0.        ],
       [1.29388419, 0.        , 0.        , 0.28976011],
       [0.        , 0.        , 0.        , 1.32298411]])

### 팬시 색인
- 정수 배열 색인?
- 정수 리스트를 이용해 여러개를 동시에 선택 가능

In [ ]:
arr = np.empty((8,4))

In [ ]:
arr

array([[6.95170012e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 1.57381196e-076,
        5.49457681e+174],
       [3.21992763e-057, 3.21691333e-057, 1.81370839e-052,
        5.51224502e-144],
       [3.59751658e+252, 3.42032083e+169, 3.51147619e+151,
        1.04918960e-153],
       [7.69165785e+218, 5.04621343e+180, 7.49874301e+247,
        2.59903827e-144],
       [4.16150731e-061, 2.57161428e+184, 9.14212225e+169,
        2.33777508e-052],
       [3.98450681e+252, 6.00736842e-067, 5.16823468e+097,
        9.75035693e-072],
       [3.41912922e+126, 1.28625693e+248, 9.46215455e-053,
        1.03723812e-314]])

In [ ]:
arr[0]

array([6.95170012e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [ ]:
for i in range(8):
    arr[i] = i

In [ ]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[1,2,3,4]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [ ]:
arr[[2,1,5,4]]

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [ ]:
arr[[2,-1,5,4]]

array([[2., 2., 2., 2.],
       [7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [ ]:
arr_8 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [ ]:
arr_8.shape

(4, 3)

In [ ]:
arr_8[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr_8[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [ ]:
arr_8[...,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [ ]:
arr = np.empty((10,3,5,8,4))

In [ ]:
arr

array([[[[[ 6.92581711e-310,  6.92581711e-310,  6.95331468e-310,
            6.95331468e-310],
          [ 5.43472210e-323,  0.00000000e+000,  2.22507386e-308,
            4.94065646e-324],
          [ 3.81425647e-315,  2.22507386e-308,  9.88131292e-324,
            9.79932320e-313],
          ...,
          [ 2.08600674e-308,  2.47032823e-323,  7.50043435e+247,
            8.20230779e-307],
          [ 4.17201349e-309,  2.96439388e-323,  1.89130745e+219,
            2.65294172e+180],
          [ 1.47129113e+224,  4.84184333e-322,  6.39708734e-308,
            3.45845952e-323]],

         [[ 6.28927877e+252,  5.72735383e-310,  1.39067116e-308,
            3.95252517e-323],
          [ 9.53545055e-307,  3.05947656e-308,  4.44659081e-323,
            1.53609058e+171],
          [ 5.18093678e-310,  1.80787251e-308,  4.94065646e-323,
           -2.19448357e-132],
          ...,
          [-7.46028900e-078, -3.23221779e-248,  1.96698084e+233,
            3.56939937e+150],
          [-1.5999

In [ ]:
arr[..., -1:]

array([[[[[ 6.95331468e-310],
          [ 4.94065646e-324],
          [ 9.79932320e-313],
          ...,
          [ 8.20230779e-307],
          [ 2.65294172e+180],
          [ 3.45845952e-323]],

         [[ 3.95252517e-323],
          [ 1.53609058e+171],
          [-2.19448357e-132],
          ...,
          [ 3.56939937e+150],
          [ 0.00000000e+000],
          [ 1.99376588e-016]],

         [[ 9.49646285e+164],
          [ 0.00000000e+000],
          [ 0.00000000e+000],
          ...,
          [ 0.00000000e+000],
          [ 0.00000000e+000],
          [-1.68409513e+159]],

         [[-6.66085898e-254],
          [-7.27030016e+106],
          [ 0.00000000e+000],
          ...,
          [ 0.00000000e+000],
          [ 0.00000000e+000],
          [ 0.00000000e+000]],

         [[ 0.00000000e+000],
          [-2.58279194e+286],
          [ 0.00000000e+000],
          ...,
          [ 0.00000000e+000],
          [ 8.19081669e+173],
          [-4.38996996e-052]]],


        [[[ 0

In [ ]:
# 예제
# wait....

- 특정한 row 를 선택하고 싶다면 그냥 원하는 순서가 명시된 정수가 담긴 ndarray 나 list를 넘기면 된다.

## 1.6 벡터화 연산 적용하기
- 배열의 여러 원소에 어떤 함수를 적용하고 싶다.
- 함수를 벡터화 시킨후 적용한다.
- vectorize 는 원소를 순회하는 for 루프를 구현한것으로 성능이 좋진 않다.
- 브로드 캐스팅이 훨신 효율적이다.

In [ ]:
# 행렬 생성
mat_1 = np.array(range(1,10))

In [ ]:
mat_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat_2 = mat_1.reshape(3,3)

In [ ]:
add_10 = lambda i: i+10

In [ ]:
vec_add_10 = np.vectorize(add_10)

In [ ]:
vec_add_10(mat_2)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
mat_2 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### 배열 전치와 축 바꾸기
- 배열 전치는 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰를 반환하는 기능
- 행과 열을 바꿔준다.

In [ ]:
# 참고 arr_1 = np.array(range(12)) 이상태에서는 transpose 가 되지 않는다. 바꿔줄 행과 열이 없다.
arr_1 = np.array(range(12)).reshape(12,1)

In [ ]:
arr_1.shape

(12, 1)

In [ ]:
arr_1.T.shape

(1, 12)

In [ ]:
arr_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
arr_1 = np.array(range(12)).reshape(3,4)

In [ ]:
arr_1.T.shape

(4, 3)

### 난수를 이용해서 ndarray를 생성하는 방법 - 5가지 존재

- np.random.radint :균일 분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일 분포에서 난수 생성
- np.random.rnadn : 가우시안 표준 정규 분포에서 난수 matrix array 생성

## 유니버설 함수 :배열의 각원소를 빠르게 처리하는 함수
- ufunc 이라고 불리기도 하는 유니버설 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수 이다.
- 유니버설 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행

### 단항 유니버설 함수
- exp, sqrt

### 이항 유니버설 함수
- maximum
- minimum
- add

이외에 다양한 종류의 함수가 존재함

## 배열지향 프로그래밍
- Numpy 배열을 사용하면 반복문을 작성하지 않고 간결한 배열 연산을 사용해 많은 종류의 데이터 처리 작업을 할 수 있다.
- 배열 연산을 사용해 반복문을 명시적으로 제거하는 기법을 벡터화 라고 한다.

- 위와 동일한 방법으로 반복문을 수행하면 큰 배열을 빠르게 처리 할수 없다.
- 같은 결과를 내는 np.where 함수가 존재 한다.

### 수학 메서드와 통계 메서드
- 합, 평균, 표준편차 를 구할수 있다.

- sum : 배열 전체 혹은 특정 축에 대한 모든 원소의 합을 계산한다. 크기가 0 인 배열에 대한 sum 결과는 0 이다.
- mean : 산술 평균을 구한다. 크기가 0인 배열에 대한 mean 결과는 Nan이다.
- std, var : 각각 표준편차(std)와 분산(var)을 구한다. 선택적으로 자유도를 줄 수 있으며 분모의 기본 값은 n 이다.
- min, max :최솟값과 최댓값
- argmin, argmax : 최소 원소의 색인값과 최대 원소의 색인값
- cumsum : 각 원소의 누적합
- cumprod : 각 원소의 누적곱

### 블리언 배열을 위한 메서드

- any와 all 메서드는 불리언 배열에 유용하다.
- any : 하나 이상의 값이 True 인지 검사
- all : 모든 원소가 True 인지 검사

### 정렬

### 집합 관련함수
- numpy는 1차원 ndarray를 위한 몇 가지 기본적인 집합 연산을 제공한다.
    - unique : 중복된 원소릴 제거한뒤 정렬하여 반환
    - intersec1d : 배열 x와 y에 중복
    - union1d : 두 배열의 합집합
    - setdiff1d :두 배열의 차집합

## 배열 데이터의 파일 입출력
- np.save
- np.load

- 여러개의 배열을 압축된 형태로 저장
    - np.savez
    - np.savez_compressed
    - 두개가 비슷한듯

## 선형대수
- 행렬의 곱셈, 분할, 행렬식에 관한 연산을 알아보자.


### linalg 모듈
- 행렬의 분할과 역행렬, 행렬식과 같은 함수를 포함하고 있다.

- diag : 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나, 1차원 대각선 원소로 하고 나머지는 0으로 채운 단위행렬을 반환한다.
- dot : 행렬 곱셈
- trace : 행렬의 대각선 원소의 합을 계산 한다.
- det : 행렬식을 계산한다.
- eig : 정사각 행렬의 고윳값과 고유 벡터를 계산하다.
- inv : 정사각 행렬의 역행렬을 계산한다.
- qr : QR분해를 계산한다.
- svd : 특잇값 분해(SVD)를 계산한다.
- solve : A가 정사각 행렬일때 Ax = b를 만족하는 x를 구한다.
- lstsq : Ax = b 를 만족하는 최소 제곱해를 구한다.

http://elearning.kocw.net/contents4/document/lec/2013/Chungbuk/LeeGeonmyeong1/13.pdf

- 점곱 계산

- 행렬 덧셈과 뺄셈

- 행렬 곱셈

- 역행렬
    - 정방행렬의 역행렬 계산

- 행렬의 랭크 구하기

- rank 는 선형 독립적인 행 또는 열의 개수. 특이값 분해를 통해서 계산한다.
- ndim 은 행렬의 차원만을 나타낸다.

- 행렬식 계산하기

- 행렬의 대각 원소 추출하기

# 고급 Numpy

## ndarray배열 재형성 하기
- 배열의 모양을 변환하려면 배열의 인스턴스 메서드인 reshape 메서드에 새로운 모양을 나타내는 튜플을 넘기면 된다.

- reshape 에 넘기는 값 중 하나가 -1이 될 수도 있는데 이경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 된다.
- -1은 가능한 많이라는 의미로 사용된다.
- magic keyword

- 다차원 배열을 낮은 차원으로 변환하는 것은 **평탄화** 라고 한다.

# 배열 이어붙이고 나누기

### 브로드캐스팅
- 브로드캐스팅은 다른 모양의 배열 간의 산술 연산을 어떻게 수행해야 하는지 설명한다.

- 여기서 스칼라 값 4는 곱셈 연산 과정에서 배열의 모든 원소로 브로드캐스트 되었다.

#### 브로드캐스팅 규칙
- 각차원에 대해 축의 길이가 일치하거나 둘 중 하나의 길이가 1이라면 두 배열은 브로드 캐스팅 호환이다.